version: "3"
services:
  db:
    image: mdillon/postgis:11
    container_name: "postgis11"
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
volumes:
  dbdata:
